// Copy this file to scripts/firebase-config.js and replace placeholders.
// Do not commit scripts/firebase-config.js.
window.__PREPIFY_PUBLIC_CONFIG__ = {
  NEXT_PUBLIC_FIREBASE_API_KEY: "REPLACE_WITH_PUBLIC_FIREBASE_API_KEY",
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "REPLACE_WITH_FIREBASE_AUTH_DOMAIN",
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "REPLACE_WITH_FIREBASE_PROJECT_ID",
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "REPLACE_WITH_FIREBASE_STORAGE_BUCKET",
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "REPLACE_WITH_FIREBASE_MESSAGING_SENDER_ID",
  NEXT_PUBLIC_FIREBASE_APP_ID: "REPLACE_WITH_FIREBASE_APP_ID",
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "REPLACE_WITH_FIREBASE_MEASUREMENT_ID",
  NEXT_PUBLIC_GA_ID: "REPLACE_WITH_GA_OR_GTAG_ID"
};
